### ISSUE TITLE
In Stock error & Default Pincode

### ISSUE THREAD

**Issue by rajatsingh828** [AmmeySaini/Flipkart-Notifier#1]
I have added products URL of 4 different categories

Temporarily unavailable,
Coming soon,
Not deliverable,
In stock.

As Not Deliverable does not show Notify me button , script recognise it as "In Stock" 

Maybe this issue can be solved by input of multiple pincodes verifying that if its in stock and then send message.

**Comment by 0xjas0** [comment]
Fixed with new update
