### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by rajatsingh828** [AmmeySaini/Flipkart-Notifier#2]
There is a error while running script.after 4-6 hours.

Error :-

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\flipkart\fk.py", line 33, in main
    if soup.find('button', class_ = '_2AkmmA _3-iCOr wvj5kH').text == 'NOTIFY ME':
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\flipkart\fk.py", line 41, in main
    if soup.find('button', class_ = '_2AkmmA _2Npkh4 _2MWPVK').text == ' ADD TO CART':
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\flipkart\fk.py", line 69, in <module>
    main()
  File "C:\Users\Administrator\Desktop\flipkart\fk.py", line 65, in main
    if soup.find('button', class_ = '_2AkmmA _2Npkh4 _2MWPVK _18WSRq')['disabled']:
TypeError: 'NoneType' object is not subscriptable

**Comment by 0xjas0** [comment]
The above error might have occurred due to ip blockage or server might have flagged the requests for some time
Fix(Might Work) -
Try increasing script sleep time or give it a break after some hours.

**Comment by rajatsingh828** [comment]
> The above error might have occurred due to ip blockage or server might have flagged the requests for some time
> Fix(Might Work) -
> Try increasing script sleep time or give it a break after some hours.

After posting this issue.

Script ran for 30 mins and shown this error and within a min ran the script again and it worked for straight 6 hours , both 5 min refresh time and no code changes.

**Comment by 0xjas0** [comment]
As i stated above it can be server side issue. Your ip might have been blocked for temporary period of time. You can try using VPN it might solve your issue
