### ISSUE TITLE
Error while feeding all information clearly

### ISSUE THREAD

**Issue by Roshankumar2** [AmmeySaini/Flipkart-Notifier#4]
![err](https://user-images.githubusercontent.com/67075491/88237310-a4332080-cc9c-11ea-9809-7d86dccc528b.png)

**Comment by Roshankumar2** [comment]
its like during the first exception otherone exception also start thatsy it givea error

**Comment by 0xjas0** [comment]
You haven't added your telegram username for receiving notifications for the stock

**Comment by Roshankumar2** [comment]
![ban](https://user-images.githubusercontent.com/67075491/88343074-32bba680-cd5e-11ea-88f4-40a406832cce.png)
i got ban
