### ISSUE TITLE
Telegram notification

### ISSUE THREAD

**Issue by vjaykrsna** [AmmeySaini/Flipkart-Notifier#5]
There us no detailed information on how to use this. I have set it up on termux but hmI don't know how to use it to get notified on telegram when my product comes in stock

**Comment by 0xjas0** [comment]
There's always README.MD

**Comment by vjaykrsna** [comment]
But I don't know where to paste my telegram api and has in fk.py

**Comment by vjaykrsna** [comment]
BTW I am using termux on Android
