### ISSUE TITLE
Telegram notification issue

### ISSUE THREAD

**Issue by sparkyvicky** [AmmeySaini/Flipkart-Notifier#6]
hello Ammey, Script is working fine. Telegram notification is comes under my saved message. Anyway to get that under by a bot?

**Comment by 0xjas0** [comment]
you can get it in your channel but you won't get notified for it.
to get yourself notified you need to create a secondary id on telegram and add it to the channel as subscriber, now whenever script will post you will get notification on your secondary id

**Comment by sparkyvicky** [comment]
How to subscribe?i don't get it. Please explain

**Comment by vjaykrsna** [comment]
BTW I am using termux on android

**Comment by vjaykrsna** [comment]
> hello Ammey, Script is working fine. Telegram notification is comes under my saved message. Anyway to get that under by a bot?

Bro can you tell me how to get notifications on telegram I don't know where to paste my api amd hash IDs
