### ISSUE TITLE
Adding support for dotenv

### ISSUE THREAD

**Issue by sank8dalvi** [AmmeySaini/Flipkart-Notifier#9]
I have few ideas that I would like to contribute to this repository.
1. Getting variables like flipkart link, pincode, telegram api details username from dotenv
2. If the details doesn't exist in dotenv then ask them from the user and overwrite dotenv so they don't have to type again when they run the script again.
3. This feature will save a lot of time by directly reading the variables from environment instead of asking from command line everytime.
I plan to use python-dotenv for the above features.

Please assign me this issue so that I can create the PR for these features.

**Comment by 0xjas0** [comment]
It's a great idea to work on
But I'm no longer maintaing this project but the idea seems to be best, you are good to go 😊

**Comment by sank8dalvi** [comment]
Thank you so much for letting me contribute to your repository. 
I have created PR #10 to add this feature.
